
CREATE TABLE MLE_PERM_DEPLOYMT_AUDIT(
   RECORD_KEY TEXT PRIMARY KEY NOT NULL,
   PERM_FILE_NAME       TEXT NOT NULL,
   PERM_FILE_TYPE  TEXT NOT NULL,
   DEPLOYMT_START_TIME TEXT NOT NULL,
   DEPLOYMT_END_TIME TEXT ,
   PERM_DEPLOYMT_STATUS TEXT NOT NULL
);